[Material]
type = "gas"
name = "fire"
ui_name = "Fire"
color = "EB982AFF"
density = -2000
lifespan = 50
expiration = [25, "smoke"]

[[Reaction]]
chance = 1
reactant = "oil"
products = ["fire", "fire"]


# [[Reaction]]
# chance = 1
# input = ["fire", "[flammable]"]
# output = ["fire", "fire"]

# [[Reaction]]
# chance = 5
# input = ["fire", "[flammable]"]
# output = ["smoke", "fire"]
