[Material]
type = "gas"
name = "fire"
ui_name = "Fire"
color = "EB982AFF"
# density = 0
lifespan = 50
expiration = [5, "smoke"]

[[Reaction]]
chance = 1
input = ["fire", "[flammable]"]
output = ["fire", "fire"]

[[Reaction]]
chance = 5
input = ["fire", "[flammable]"]
output = ["smoke", "fire"]