[Material]
type = "liquid"
name = "iron_molten"
ui_name = "Molten Iron"
color = "a19d94ff"
# texture = "assets/textures/iron.png"

[[Reaction]]
chance = 1
input_1 = "iron_molten"
input_2 = "water"
output_1 = "iron"
output_2 = "steam"