[Material]
name = "oil"
ui_name = "Oil"
type = "liquid"
color = "573b2a88"
density = 900
viscosity = 10
tags = ["flammable"]

[[Reaction]]
chance = 1
reactant = "fire"
products = ["fire", "fire"]

[[Reaction]]
chance = 10
reactant = "water"
products = ["oil", "water_dirty"]

[[Reaction]]
chance = 50
reactant = "water_dirty"
products = ["water_dirty", "water_dirty"]

[[Reaction]]
chance = 2
reactant = "lava"
products = ["lava", "fire"]


# [[Reaction]]
# chance = 30
# input = ["oil", "fire"]
# output = ["fire", "fire"]
