[Material]
name = "oil"
ui_name = "Oil"
type = "liquid"
color = "573b2a88"
density = 900
viscosity = 10
tags = ["flammable"]

[[Reaction]]
chance = 10
reactant = "water"
products = ["oil", "water_dirty"]

[[Reaction]]
chance = 25
reactant = "water_dirty"
products = ["water_dirty", "water_dirty"]
