[Material]
name = "oil"
ui_name = "Oil"
type = "liquid"
color = "573b2a88"
density = 900
viscosity = 10
tags = ["flammable"]

[[Reaction]]
chance = 10
input = ["oil", "water"]
output = ["oil", "water_dirty"]

# [[Reaction]]
# chance = 2
# input = ["oil", "lava"]
# output = ["smoke", "fire"]

# [[Reaction]]
# chance = 30
# input = ["oil", "fire"]
# output = ["fire", "fire"]

[[Reaction]]
chance = 150
input = ["oil", "water_dirty"]
output = ["water_dirty", "water_dirty"]