[Material]
type = "liquid"
name = "water"
ui_name = "Water"
color = "0197f477"

[[Reaction]]
chance = 1
input = ["water", "lava"]
output = ["steam", "stone"]

[[Reaction]]
chance = 1
input = ["water", "[rustable]"]
output = ["water", "[rustable]_rust"]

[[Reaction]]
chance = 5
input = ["water", "acid"]
output = ["water", "water"]