[Material]
name = "water_dirty"
ui_name = "Dirty Water"
type = "liquid"
density = 950
color = "35607b88"
tags = ["corrodible"]

[[Reaction]]
chance = 5
input = ["dirty_water", "[rustable]"]
output = ["dirty_water", "rust"]
