[Material]
name = "gunpowder"
ui_name = "Gunpowder"
type = "powder"
color = "202022ff"
offset = 25
softness = 10
tags = ["flammable", "explosive", "corrodible"]

[[Reaction]]
chance = 1
input = ["gunpowder", "lava"]
output = ["smoke", "lava"]